services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.reactUI
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules  
    stdin_open: true
    restart: always
    depends_on:
      - db
    networks:
      - mern-stack-net
  server: 
    build:
      context: ./server
      dockerfile: Dockerfile.node
    ports: 
      - "4000:4000"    #external:internal 
    volumes: 
      - ./server:/app 
      - /app/node_modules
    depends_on:
      - db
    networks:
      - mern-stack-net
  db:
    volumes:
      - mongo-data:/data/db
    image: mongo:latest
    ports:
      - "27017:27017" 
    networks:
      - mern-stack-net

networks:
  mern-stack-net: 
volumes:
   mongo-data:
